//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace site {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("site.Msg", typeof(Msg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto introduzido não é válido..
        /// </summary>
        internal static string Contacto_invalido {
            get {
                return ResourceManager.GetString("Contacto_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O funcionário não existe..
        /// </summary>
        internal static string Funcionario_inexistente {
            get {
                return ResourceManager.GetString("Funcionario_inexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número tem de ser positivo..
        /// </summary>
        internal static string Numero_tem_ser_positivo {
            get {
                return ResourceManager.GetString("Numero_tem_ser_positivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string indicada não pode estar vazia..
        /// </summary>
        internal static string String_vazia {
            get {
                return ResourceManager.GetString("String_vazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de funcionário escolhido não existe..
        /// </summary>
        internal static string Tipo_funcionario_inexistente {
            get {
                return ResourceManager.GetString("Tipo_funcionario_inexistente", resourceCulture);
            }
        }
    }
}
