//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Msg", typeof(Msg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O comando não pode ser aplicado a este funcionário..
        /// </summary>
        internal static string Comando_incorreto_para_agregadp {
            get {
                return ResourceManager.GetString("Comando_incorreto_para_agregadp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O contacto introduzido não é válido..
        /// </summary>
        internal static string Contacto_incorreto {
            get {
                return ResourceManager.GetString("Contacto_incorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A coleção de contactos a remover não pode intercetar a coleção de contactos a adicionar..
        /// </summary>
        internal static string Contactos_intercetados {
            get {
                return ResourceManager.GetString("Contactos_intercetados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O NIF introduzido não é válido..
        /// </summary>
        internal static string Nif_invalido {
            get {
                return ResourceManager.GetString("Nif_invalido", resourceCulture);
            }
        }
    }
}
